name: AI-assisted
on:
  pull_request:
    types: [ready_for_review]

jobs:
  summary:
    name: PR Summary
    if: github.actor != 'ospo-renovate[bot]'
    runs-on: [ubuntu-latest]
    steps:
      - uses: SAP/ai-assisted-github-actions/pr-summary@93162bffd6b396623ffa5b20e4666e427db88414 # v3.0.2
        with:
          aicore-service-key: ${{ secrets.AICORE_SERVICE_KEY }}
          model: gpt-4o
          exclude-files: package-lock.json
          display-mode: append
          header-text: "---"

  review:
    name: PR Review
    if: github.actor != 'ospo-renovate[bot]'
    runs-on: [ubuntu-latest]
    steps:
      - uses: SAP/ai-assisted-github-actions/pr-review@93162bffd6b396623ffa5b20e4666e427db88414 # v3.0.2
        with:
          aicore-service-key: ${{ secrets.AICORE_SERVICE_KEY }}
          model: gpt-4o
          exclude-files: package-lock.json
